[2024-02-14T20:03:09.839+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_table_in_pg_db scheduled__2024-02-08T00:00:00+00:00 [queued]>
[2024-02-14T20:03:09.847+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_table_in_pg_db scheduled__2024-02-08T00:00:00+00:00 [queued]>
[2024-02-14T20:03:09.847+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-02-14T20:03:09.897+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_table_in_pg_db> on 2024-02-08 00:00:00+00:00
[2024-02-14T20:03:09.901+0000] {standard_task_runner.py:60} INFO - Started process 58317 to run task
[2024-02-14T20:03:09.906+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator', 'create_table_in_pg_db', 'scheduled__2024-02-08T00:00:00+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/pg_op_dag.py', '--cfg-path', '/tmp/tmp__3u0805']
[2024-02-14T20:03:09.908+0000] {standard_task_runner.py:88} INFO - Job 283: Subtask create_table_in_pg_db
[2024-02-14T20:03:09.998+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator.create_table_in_pg_db scheduled__2024-02-08T00:00:00+00:00 [running]> on host codespaces-57ffd0
[2024-02-14T20:03:10.089+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='raghu' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='create_table_in_pg_db' AIRFLOW_CTX_EXECUTION_DATE='2024-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-08T00:00:00+00:00'
[2024-02-14T20:03:10.089+0000] {sql.py:276} INFO - Executing: create table if not exists dag_runs (name varchar(50), age int)
[2024-02-14T20:03:10.092+0000] {base.py:83} INFO - Using connection ID 'postgres_db_connection' for task execution.
[2024-02-14T20:03:10.113+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/python/3.10.13/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 151, in _hook
    hook = conn.get_hook(hook_params=self.hook_params)
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/models/connection.py", line 365, in get_hook
    hook_class = import_string(hook.hook_class_name)
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 35, in import_string
    module_path, class_name = dotted_path.rsplit(".", 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
[2024-02-14T20:03:10.117+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator, task_id=create_table_in_pg_db, execution_date=20240208T000000, start_date=20240214T200309, end_date=20240214T200310
[2024-02-14T20:03:10.162+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 283 for task create_table_in_pg_db ('NoneType' object has no attribute 'rsplit'; 58317)
[2024-02-14T20:03:10.206+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-14T20:03:10.215+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
